version: '3.8'
services:
  grpc_server:
    build:
      context: ..
      dockerfile: container/grpcserver/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server
  grpc_client:
    build:
      context: ..
      dockerfile: container/grpcclient/Dockerfile
    depends_on:
      - grpc_server
